### ISSUE TITLE
Make statues, disks etc work as anomaly entity containment

### ISSUE THREAD

**Issue by feldoh** [feldoh/PawnStorages#14]

**Comment by keyz182** [comment]
Wanted to do a little rimrim modding, but couldn't think of my own idea, so decided to look at this. 

I've got the base-work done for this, statues being valid containment for entities, and being able to put them on there. 

So I now have a question on the specifics. When an entity is captured onto a statue, should it be "frozen" like a pawn is, or should it remain "unfrozen" as with normal holding platforms?

**Comment by feldoh** [comment]
I'd say it should be frozen. The general purpose of the mod is to freeze stuff, mostly for performance reasons and it doesn't make sense you wouldn't be able to stick entities in them so they should follow the same rules.

It also allows for a cool aesthetic of like an eldritch throne room with gargoylesque statues of entities around the throne

There's some extra considerations though:
* Should there be a way to get bioferrite (slower than normal or 0)
  * My inclination is no, but like the Jeweled stand adds the extra button, there could be a extraction-stand made with bioferrite that slowly drains them
* Should they be able to break out (and if so should the containment strength improvement things work on them)
  * My inclination is no, but, to combine with the other question. If there's a way to get a resource from them maybe they should be able to break out to counter that, so if there were to be an extraction stand they should be able to break out of that.
  * Alternatively a setting to enable breakouts so people can choose their playstyle.

**Comment by feldoh** [comment]
Also side comment, thanks a lot for picking it up!
