### ISSUE TITLE
Farm buildings

### ISSUE THREAD

**Issue by feldoh** [feldoh/PawnStorages#15]
Add a "farm" building
find a way to make people input food etc.
Put in ten muffalo, get products out etc.

**Comment by keyz182** [comment]
I started working on this [here](https://github.com/feldoh/PawnStorages/issues/15). Not sure I'll have time to finish it up though. Bank holiday weekend is over, so back to work. Might have some evening time, but not sure. 

Current state - 
- There's a farm building
- You can put multiple animals in it
- Nutrition required is calculated
- (In theory) nutrition available calculated
- (In theory) nutrition is dropped down on `Tick()`
- Can't add nutrition
- Storage tab button doesn't show up
- Float menu orders are buggy - sometimes shows Farm and store options, sometimes locks you out of storing anything
- No drops yet

The float menu bit is kinda expected, I just quickly copy/pasted there to get an option going with a view to cleaning it up later. Storage tab, and the inability to add nutrition is what I'm stuck on right now. I think once that's sorted, and the nutrition use is validated as working, it's really just a once-over of the orders to clear up, and decide how to drop the products.

**Comment by keyz182** [comment]
I guess it could be moved out of being art and into being a normal building? Drop the quality capability? And probably a new set of images :)

**Comment by feldoh** [comment]
Absolutely this should be a normal building, it's only the statues that are art. Check out the pawn doors instead of the statues or the digitizer platform, door onto a farm would be fine but then there's the whole how to feed thing, I think it needs an actual building so that it can be several cells wide to allow for hoppers maybe? That was my thinking. Can just be a plain box, maybe quite large in one dimension like 2x4 with an animal flap on the front. Maybe 12 slots. So hoppers can be down the side.

Could have a graphic version that has their heads poking out the other side sized to fit so 2xN where N is number of slots for all the graphics but that's more performance heavy and work so v1, battery farm; I'm more than happy with a flap or a box.
