### ISSUE TITLE
Throwable capture spheres

### ISSUE THREAD

**Issue by feldoh** [feldoh/PawnStorages#34]
The capture crystals are good but wouldn't it be cool if you could throw them and have a capture chance based on combat power and so you could cap at a distance

**Comment by keyz182** [comment]
The throwable part of this is done, but not so much the combat power bit. That's covered by the idea of graded spheres though, so I think we can close this out.

**Comment by keyz182** [comment]
The throwable part of this is done, but not so much the combat power bit. That's covered by the idea of graded spheres though, so I think we can close this out.
