### ISSUE TITLE
More customisable auto slaughter

### ISSUE THREAD

**Issue by feldoh** [feldoh/PawnStorages#47]
> a quick suggestion, with the breeding farms you could do to make it so that it slaughters the youngest first as im trying to farm chickens but the chicks arnt given the time to grow up before the limit i set slaughters them

> Oldest first is intentional so that they rotate through otherwise you'd have a bunch of ancient ones that never get slaughtered. It's the oldest per category too (e.g. adult) which means if you made it youngest then the second a new pawn aged up into a category they'd be the youngest in that category and if over the adult limit would immediately be the slaughtered one. But oldest doesn't work for the same reason, if they're oldest in the non-adult category they'll be culled before ever getting into adult so I think neither route works in the general case. If you set a low max for the adults then when a new chick aged up into adult it'd cull the older adults, then you can just let the young limit be infinite. You can also change the breeding scale in the mod-settings to slow down the breeding to make it more viable.

Inverting it for adult sort of works but culling youngest juvenile and oldest adult means you'd cull your oldest dragons which is a terrible idea. So it needs to be more customisable.

Solution:
- Add two new tickboxes to each row of the autoslaughter config to allow users to pick per animal type and age grouping, whether oldest or youngest should go first.
- Defaults should be youngest first for juvenile and eldest first for adult.

**Comment by keyz182** [comment]
Went with a toggle for each Age/Gender combo, and one for "all". Selectable per `PawnDefKind`

![Screenshot 2024-08-16 183659](https://github.com/user-attachments/assets/c4c81c16-d918-469d-83ed-4c5c62e670ef)
